### ISSUE TITLE
Download PetScan results directly from PetScan

### ISSUE THREAD

**Issue by eggpi** [Bam92/gsoc18#1]
I see this repository has a pre-downloaded PetScan result (petscan.json), and the Javascript code downloads and displays it in the client side. That's a nice start!

For the worklist tool, it would be nice if users could prepare PetScan queries and then give us an URL or ID (like 3316252 for https://petscan.wmflabs.org?psid=3316252), instead of pre-downloading the results to a JSON file and then giving that file to us.

That would allow us to re-download the PetScan query every once in a while in the server, "refreshing" the worklist without needing the user to do anything, and the client side (Javascript) would just query the server for the latest "version" of the worklist.

PetScan allows you export a given query to json by adding `&format=json` to the URL:

https://petscan.wmflabs.org?psid=3316252&format=json

Can you please sketch a server-side component that can download the JSON directly from PetScan? You could just make it print the article titles as in your Javascript. It would be a good idea to do it in Python if you can, but any language that is supported in Toolforge is fine.

**Comment by Bam92** [comment]
Thank you @eggpl for your comment.

I am not sure that I understand you well. Do you mean that I do everything in Python or front in JS and back in Python? And if it is this last one, the server-side program must be able to be updated (if needed) everytime the page is reloaded?

**Comment by eggpi** [comment]
> Do you mean that I do everything in Python or front in JS and back in Python?

The second: the tool would have a font end in JS and a back end in Python.

My suggestion in this issue was that you try writing a (very) simplified version of the server: a little Python script that receives as input a PetScan ID, queries PetScan using that ID, getting back JSON results, and just prints the resulting articles.

Since this is just meant as a small warm-up task, there's no need to make your Python code actually serve the articles to your JS (but of course you can, if you want to!). The Python code can be just an independent script in this repository, we just want to try sketching small pieces of the tool for now :)

> And if it is this last one, the server-side program must be able to be updated (if needed) everytime the page is reloaded?

The way I'm imagining it is:

1. A user goes on PetScan and creates a query. For example, the query may represent "articles about Kinshasa that have not been edited in the last week".
2. The user copies the ID of the query from PetScan, goes to the worklist tool and gives us that ID. The user creates a worklist called "My Kinshasa worklist".
3. With the ID, our Python server can query PetScan to get the articles. Those will be the articles in "My Kinshasa worklist".
4. When a user accesses the worklist tool and chooses to work on the worklist "My Kinshasa worklist", the JS asks the server for the list of articles in that worklist, and shows it to the user.
5. At any time, the server can query PetScan again using the ID to "refresh" the list of articles and keep it up-to-date. We could do this at every page reload in the client, or just do it every day, or something like that.

Does that help? Let me know if you have more questions!

**Comment by Bam92** [comment]
Do have a look at the script I pushed (server.py). It is a very simple version that write the json output from PetScan to a file (test.json). It is a minimalist version of the code, just for test using this PSID 3316252 (it is not yet dynamic).

There are some issues that occur:

- the output is a complex json file, and I'm wondering how to parse it in order to print title attributes

- the language: how do I now the home wiki used for such query? I see something as len. In french we have this lfr? Do I have to implement so algo that will decode len to en, lfr to fr, etc.?

I am still working on!

**Comment by eggpi** [comment]
Nice, thanks! This is definitely in the right direction. Here's a couple of hints for your questions:

- What kind of Python object is `json.loads` returning? The json module did _parse_ the text and turned into something useful in your program, but you don't seem to be using it.
- Good question! For this demo we can just assume enwiki.
    - If you look at the JSON, you'll see that the "len" is a number, and it's in fact a different number for each page even though they are all in the same language (I was querying enwiki in PetScan), so it's not an "encoding" of the language. It's actually the **LEN**gth of the article contents, in bytes. You can also see it in the query results in the PetScan UI (https://petscan.wmflabs.org/?psid=3316252).
    - A few things to think about: if PetScan won't give us the language for a query, how will we know it in the final tool? Where would we store it? When would we need it?

Also, you don't need to `os.chdir` into a directory to write your file there, just:

```python
with open(os.path.expanduser("~/public_html/gsoc18/test.json")) as f:
    print(data, file=f)
```

should work. If you're not familiar with `os.path.expanduser` and other functions in `os.path`, have a quick look at [the documentation](https://docs.python.org/3/library/os.path.html). It's a very useful module!

**Comment by Bam92** [comment]
- `json.load` is returning a dict. Do you mean I've not to use the parsed text?

-  Here is what I think it would help. The program will have a form that asks PSID, language of the query and some other questions (if needed of course). All these info will be stored in a simple .txt|.json file. The server.py will check that file to pick up articles|pages using the PSID. The front end (JS mainly) will also check that file for query language and displays links to corresponding articles|pages

Using `os.path.expanduser` how do the script write on test.json?

**Comment by Bam92** [comment]
- `json.load` is returning a dict. Do you mean I've not to use the parsed text?

-  Here is what I think it would help. The program will have a form that asks PSID, language of the query and some other questions (if needed of course). All these info will be stored in a simple .txt|.json file. The server.py will check that file to pick up articles|pages using the PSID. The front end (JS mainly) will also check that file for query language and displays links to corresponding articles|pages

Using `os.path.expanduser` how do the script write on test.json?

**Comment by eggpi** [comment]
- You are trying to get the titles of the articles that are inside the JSON response. The dict is the parsed version of that response, so the titles should be in there somewhere. You just need to figure out how to access and print them, instead of saving the entire dict to a file.

- Cool, that's close to what I was thinking! However, "simple" text files are usually not as simple as they sound. For example:
  - If we have two users creating worklists at the same time, for example, we risk having our server overwrite the file and lose one of the worklists if we don't coordinate carefully.
  - It's not very easy to extract complex information about worklists from a text file (for example, "which worklists for frwiki have not been modified in the past 90 days" so we can delete them, or "which worklists are 90% done").

  This kind of server information is usually better suited for a database system, and [we can easily use MySQL in Toolforge](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#User_databases). Do you have any experience with that? I can point you to some reading material if you want.

- `os.path.expanduser` just converts `'~'` into `'/home/bam92/'`. I think you can just use the code I provided in my previous comment if you want to write to `test.json`, right? I've just edited it a little but I think it should be correct.

**Comment by Bam92** [comment]
- Did you try to have a look on my js scripts (script.js especially)? I can now parse json file.

> You just need to figure out how to access and print them, instead of saving the entire dict to a file.

I save into a file because I use JS to print the titles. Do you think I can abandon JS and use only Py?

- You right, we have to use a dbms for that. I'll have a look at MySQL as suggested above.

- Everything is OK with `os.path.expanduser` now.

What's the next step then?

**Comment by Bam92** [comment]
- Did you try to have a look on my js scripts (script.js especially)? I can now parse json file.

> You just need to figure out how to access and print them, instead of saving the entire dict to a file.

I save into a file because I use JS to print the titles. Do you think I can abandon JS and use only Py?

- You right, we have to use a dbms for that. I'll have a look at MySQL as suggested above.

- Everything is OK with `os.path.expanduser` now.

What's the next step then?

**Comment by eggpi** [comment]
Oh, I see. That's totally fine for this warm-up task, well done!

> Do you think I can abandon JS and use only Py?

For the final tool, what I think we'll end up doing is:

- We query PetScan from the server, in Python, parse the JSON and extract information from it.
- We store that information (for example, the list of articles) in the database.
- Later on, the server reads that information from the database and sends it to the JS, which uses it to render the page.

So we'll want both JS and Python, and this repository contains a nice example of how that would work :)

> What's the next step then?

Definitely read up on MySQL, and possibly also [Flask](http://flask.pocoo.org/) if you're not familiar with it please. If you are comfortable with some other Python framework (like [Django](http://djangoproject.com)) we could use that, but if not, Flask is the easier to get started.

Other than that, you could just start thinking about and writing your proposal, and I'll be happy to give it an early look and make comments! The [GSoC participant information](https://www.mediawiki.org/wiki/Google_Summer_of_Code/Participants) page for MediaWiki has some tips and links to previously accepted proposals for inspiration.

Do let me know if you have questions!

**Comment by Bam92** [comment]
Thank you indeed. 

I'll be writing my proposal soon and at the same time thinking about specs (I'll put you some questions to get my specs well done).

I think we'll be using Flask as it is not a big tool (?) that would require us to use a full framework.
